app:
  name: fitness_tracking_app
  env: dev
postgres:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "14022014"
  database: "fitness_traking"
server:
  http:
    host: "localhost"
    port: "8080"